import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

// ─── PDF Color Palette ────────────────────────────────────────────────────────
const PDF_DARK   = "#1a1a1a";
const PDF_ORANGE = "#f97316";
const PDF_RED    = "#ef4444";
const PDF_AMBER  = "#f59e0b";
const PDF_GREEN  = "#16a34a";
const PDF_WHITE  = "#ffffff";
const PDF_MUTED  = "#888888";

// ─── Helpers ──────────────────────────────────────────────────────────────────

function hex(h) {
  const r = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(h);
  return r ? [parseInt(r[1], 16), parseInt(r[2], 16), parseInt(r[3], 16)] : [0, 0, 0];
}

function scoreColor(score) {
  if (score < 4)  return PDF_RED;
  if (score <= 6) return PDF_AMBER;
  return PDF_GREEN;
}

function formatAuditDate(ts) {
  return new Date(ts).toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });
}

function stripMarkdown(text) {
  return text
    .replace(/^#{1,6}\s*/gm, "")           // ## headings
    .replace(/\*\*(.*?)\*\*/gs, "$1")       // **bold**
    .replace(/\*(.*?)\*/gs, "$1")           // *italic*
    .replace(/^-{3,}\s*$/gm, "────────")    // --- dividers → readable line
    .replace(/```[\s\S]*?```/g, "")         // ```code blocks```
    .replace(/`([^`\n]+)`/g, "$1")          // `inline code`
    .replace(/^\s*[-*+] /gm, "• ")          // bullet list markers
    .trim();
}

// ─── Main Export ──────────────────────────────────────────────────────────────

/**
 * generateAuditPdf
 * Takes a Convex seoAudits document and returns a configured jsPDF instance.
 * Caller: pdf.output("bloburl") to get an inline-viewable URL.
 */
export function generateAuditPdf(audit) {
  const doc   = new jsPDF({ unit: "pt", format: "letter" });
  const PW    = doc.internal.pageSize.getWidth();
  const PH    = doc.internal.pageSize.getHeight();
  const M     = 48;    // margin
  const CW    = PW - M * 2;  // content width

  let y = 0; // current cursor Y

  // ── Footer ─────────────────────────────────────────────────────────────────
  // Called after all pages are built to stamp every page.
  const stampFooters = () => {
    const total = doc.getNumberOfPages();
    for (let p = 1; p <= total; p++) {
      doc.setPage(p);
      const fy = PH - 22;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7.5);
      doc.setTextColor(...hex(PDF_MUTED));
      doc.text("Generated by Anthony Tatis · anthonytatis.com", M, fy);
      doc.text(`Page ${p} of ${total}`, PW - M, fy, { align: "right" });
    }
  };

  // ── Page break guard ───────────────────────────────────────────────────────
  const guard = (needed = 80) => {
    if (y + needed > PH - 56) {
      doc.addPage();
      y = 52;
    }
  };

  // ── Section header ─────────────────────────────────────────────────────────
  const sectionHead = (label) => {
    guard(48);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(...hex(PDF_ORANGE));
    doc.text(label.toUpperCase(), M, y);
    y += 3;
    doc.setDrawColor(...hex(PDF_ORANGE));
    doc.setLineWidth(0.8);
    doc.line(M, y, M + 56, y);
    y += 14;
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...hex(PDF_DARK));
  };

  // ─────────────────────────────────────────────────────────────────────────
  // PAGE 1 — HEADER BAND
  // ─────────────────────────────────────────────────────────────────────────

  // Dark header rectangle
  doc.setFillColor(...hex(PDF_DARK));
  doc.rect(0, 0, PW, 96, "F");

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(17);
  doc.setTextColor(...hex(PDF_WHITE));
  doc.text("WCORWIN SEO AUDIT REPORT", M, 38);

  // Domain in orange
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(...hex(PDF_ORANGE));
  doc.text("wcorwin.com", M, 58);

  // Date in muted
  doc.setFontSize(10);
  doc.setTextColor(170, 170, 170);
  doc.text(formatAuditDate(audit.runAt), M, 76);

  y = 116;

  // ─────────────────────────────────────────────────────────────────────────
  // SCORE SUMMARY TABLE
  // ─────────────────────────────────────────────────────────────────────────

  const pillars = [
    ["Overall",   audit.overallScore],
    ["On-Page",   audit.onPage],
    ["Technical", audit.technical],
    ["Content",   audit.content],
    ["Local",     audit.local],
    ["Authority", audit.authority],
  ];

  autoTable(doc, {
    startY: y,
    margin: { left: M, right: M },
    tableWidth: CW,
    head: [["Pillar", "Score / 10"]],
    body: pillars.map(([label, score]) => [label, score != null ? Number(score).toFixed(1) : "—"]),
    headStyles: {
      fillColor:  hex(PDF_ORANGE),
      textColor:  hex(PDF_WHITE),
      fontStyle:  "bold",
      fontSize:   10,
      halign:     "left",
    },
    bodyStyles: {
      fontSize:   10,
      textColor:  hex(PDF_DARK),
      minCellHeight: 24,
      valign: "middle",
    },
    columnStyles: {
      0: { cellWidth: "auto", fontStyle: "bold" },
      1: { cellWidth: 100, halign: "center", fontStyle: "bold" },
    },
    didParseCell(data) {
      if (data.section === "body" && data.column.index === 1) {
        const score = pillars[data.row.index]?.[1];
        if (score != null) {
          const color = scoreColor(Number(score));
          data.cell.styles.fillColor  = hex(color);
          data.cell.styles.textColor  = hex(PDF_WHITE);
        }
      }
    },
    theme: "striped",
    alternateRowStyles: { fillColor: [248, 248, 248] },
  });

  y = (doc.lastAutoTable?.finalY ?? y) + 30;

  // ─────────────────────────────────────────────────────────────────────────
  // EXECUTIVE SUMMARY
  // ─────────────────────────────────────────────────────────────────────────

  if (audit.summary) {
    sectionHead("Summary");
    doc.setFontSize(10);
    doc.setLineHeightFactor(1.55);
    const lines = doc.splitTextToSize(audit.summary, CW);
    guard(lines.length * 16 + 20);
    doc.text(lines, M, y);
    y += lines.length * 16 + 24;
  }

  // ─────────────────────────────────────────────────────────────────────────
  // TOP RECOMMENDATIONS
  // ─────────────────────────────────────────────────────────────────────────

  if (audit.recommendations?.length > 0) {
    guard(60);
    sectionHead("Recommendations");

    audit.recommendations.forEach((rec, i) => {
      guard(36);
      const num = String(i + 1).padStart(2, "0") + ".";

      // Number in orange
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      doc.setTextColor(...hex(PDF_ORANGE));
      doc.text(num, M, y);

      // Rec text
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(...hex(PDF_DARK));
      const lines = doc.splitTextToSize(rec, CW - 28);
      doc.text(lines, M + 28, y);
      y += lines.length * 15 + 10;
    });

    y += 14;
  }

  // ─────────────────────────────────────────────────────────────────────────
  // FULL REPORT
  // ─────────────────────────────────────────────────────────────────────────

  if (audit.rawReport) {
    guard(60);
    sectionHead("Detailed Report");

    const cleaned = stripMarkdown(audit.rawReport);
    doc.setFontSize(9.5);
    doc.setLineHeightFactor(1.5);

    const paragraphs = cleaned.split(/\n{2,}/);

    paragraphs.forEach((para) => {
      const trimmed = para.trim();
      if (!trimmed) return;

      const lines = doc.splitTextToSize(trimmed, CW);
      guard(lines.length * 14 + 8);
      doc.text(lines, M, y);
      y += lines.length * 14 + 10;
    });
  }

  // ─────────────────────────────────────────────────────────────────────────
  // STAMP FOOTERS
  // ─────────────────────────────────────────────────────────────────────────

  stampFooters();

  return doc;
}
